<?php

return [
    [
        'name' => 'username',
        'title' => '短信宝账号',
        'type' => 'string',
        'content' => [],
        'value' => '15177636198',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'password',
        'title' => '短信宝密码',
        'type' => 'string',
        'content' => [],
        'value' => 'ABCD9696',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sign',
        'title' => '短信签名',
        'type' => 'string',
        'content' => [],
        'value' => '【商城平台】',
        'rule' => 'required',
        'msg' => '',
        'tip' => '例如【短信宝】',
        'ok' => '',
        'extend' => '',
    ],
];
